import { Project } from "@/models/Project";

export const projects: Project[] = [
  {
    id: "commish",
    title: "Commish",
    images: [""],
    altText: "Interface do Commish",
    category: "web",
    tools: ["React", "Next.js", "TypeScript", "Tailwind CSS", "Radix UI", "Shadcn"],
    description: "Commish é uma plataforma de gestão de comissões.",
    externalLink: "https://commish-project.vercel.app",
    repoLink: "https://github.com/ramou1/commish",
    ariaLabel: "Visitar a plataforma do Commish",
    showSlide: false,
  },
  {
    id: "impar",
    title: "Impar Climatização e Sistemas Ltda",
    images: [""],
    altText: "Site da empresa Impar Climatização e Sistemas Ltda",
    category: "web",
    tools: ["React", "Next.js", "TypeScript", "Tailwind CSS", "Radix UI", "Shadcn"],
    description: "Site da empresa Impar Climatização e Sistemas Ltda, que faz instalações de ar condicionado central e ventilação.",
    externalLink: "https://impar-site.vercel.app",
    repoLink: "https://github.com/ramou1/impar-site",
    ariaLabel: "Visitar o site da Impar",
    showSlide: false,
  },
  {
    id: "nutribot",
    title: "NutriBot",
    images: ["/images/projects/nutribot01.mov", "/images/projects/nutribot02.png", "/images/projects/nutribot03.png", "/images/projects/nutribot04.png"],
    altText: "Interface do NutriBot mostrando os assistentes NutriBot e ChefBot para recomendações nutricionais e de restaurantes",
    category: "web",
    tools: ["Next.js", "OpenAI", "TypeScript", "Tailwind CSS"],
    description: "NutriBot é uma plataforma que oferece dois assistentes inteligentes (NutriBot e ChefBot), desenvolvida durante o hackathon da empresa Brendi. O NutriBot auxilia clientes a encontrarem opções alimentares adequadas às suas necessidades específicas, enquanto o ChefBot ajuda usuários a encontrarem restaurantes e pratos que atendam às suas necessidades alimentares.",
    externalLink: "https://nutribot0.vercel.app",
    repoLink: "https://github.com/ramou1/nutribot",
    ariaLabel: "Visitar o site do NutriBot",
    showSlide: false,
  },
  {
    id: "dj-laud",
    title: "DJ Laud",
    images: ["/images/projects/laud01.mp4"],
    altText: "Site do DJ Laud de Hardtechno, Hardstyle e Trance, mostrando informações sobre próximos shows.",
    slideImage: "/images/slide02.png",
    category: "web",
    tools: ["Wix", "HTML", "CSS", "Javascript"],
    description: "Site para o DJ Laud, apresentando informações sobre próximos eventos, vídeos de shows e redes sociais.",
    externalLink: "https://laud.live",
    ariaLabel: "Visitar o site da Laud Live",
    showSlide: true,
  },
  {
    id: "terapeuta-bele",
    title: "Terapeuta Bele",
    images: ["/images/portfolio01.png"],
    altText: "Site da Terapeuta Bele, mostrando informações sobre terapias e agendamentos",
    slideImage: "/images/slide01.png",
    category: "web",
    tools: ["Wix", "HTML", "CSS", "Javascript"],
    description: "Site profissional para a terapeuta Bele, com informações sobre serviços, blog e agendamento de consultas.",
    externalLink: "https://terapeutabele.com.br",
    ariaLabel: "Visitar o site da Terapeuta Bele",
    showSlide: true,
  },
  {
    id:"rca",
    title: "RCA Contabilidade",
    images: ["/images/projects/rca01.png"],
    altText: "Site da RCA Contabilidade, mostrando informações sobre serviços contábeis",
    category: "web",
    tools: ["Wix", "HTML", "CSS", "Javascript"],
    description: "Site para a empresa de contabilidade RCA Contabilidade, apresentando serviços, blog e informações de contato.",
    externalLink: "https://rcacontabilidade.com",
    ariaLabel: "Visitar o site da RCA",
    showSlide: false,
  },
  {
    id: "miraggio-villa-branca",
    title: "Miraggio Villa Branca",
    images: ["/images/projects/miraggio.mp4"],
    altText: "Landing page do Miraggio Villa Branca, mostrando informações sobre o local.",
    category: "web",
    tools: ["Wordpress", "Elementor", "HTML", "CSS", "Javascript"],
    description: "Landing page para o empreendimento Miraggio Villa Branca da construtora Marcondes Cesar na cidade de Jacareí, apresentando formulário de contato, informações relevantes sobre a localização e infraestrutura.",
    externalLink: "https://miraggio.marcondescesar.com.br",
    ariaLabel: "Visitar o landing do Miraggio",
    showSlide: false,
  },
  {
    id: "hostelzim",
    title: "HostelZim",
    images: ["/images/portfolio02.png"],
    altText: "Interface do sistema HostelZim mostrando uma lista de quartos e clientes",
    category: "web",
    tools: ["React", "Chakra UI", "Chart.js", "Axios"],
    description: "HostelZim é um sistema web desenvolvido em React para gerenciamento de um hostel. Ele permite criar, editar, excluir e listar quartos e clientes.",
    externalLink: null,
    repoLink: "https://github.com/ramou1/hostel-system",
    ariaLabel: "Ver detalhes do sistema Fatura Online",
    showSlide: true,
  },
  {
    id: "music-chords",
    title: "Music Chords",
    images: ["/images/portfolio03.png"],
    altText: "Interface do aplicativo Music Chords mostrando uma lista de acordes e formulário de criação de acorde",
    category: "mobile",
    tools: ["Ionic", "Typescript"],
    description: "Aplicativo para salvar acordes de músicas.",
    externalLink: null,
    repoLink: "https://github.com/ramou1/music-chords-app",
    ariaLabel: "Ver detalhes do Music Chords",
    showSlide: false,
  },
  {
    id: "gimme-pizza",
    title: "Gimme Pizza",
    images: ["/images/portfolio04.png"],
    altText: "Interface do sistema de Chamados mostrando uma lista de chamados e formulário de criação de chamado",
    category: "web",
    tools: ["Angular", "Firebase"],
    description: "Sistema para gerenciar pedidos de pizza.",
    repoLink: "https://github.com/ramou1/gimme-pizza",
    ariaLabel: "Ver detalhes do sistema",
    showSlide: false,
  },
  {
    id: "purificatta2",
    title: "Purificatta",
    images: ["/images/portfolio07.png"],
    altText: "Interface do aplicativo Purificatta exibindo gerenciamento de assinaturas de purificadores de água",
    category: "mobile",
    tools: ["Ionic", "Typescript", "SASS", "Firebase"],
    description: "Aplicativo para clientes da Purificatta, permitindo gerenciamento de planos e acompanhamento de serviços.",
    externalLink: "https://play.google.com/store/apps/details?id=br.com.purificatta.app",
    ariaLabel: "Ver detalhes do Purificatta",
    showSlide: false,
  },
  {
    id: "purificatta-adesao2",
    title: "Purificatta Adesão",
    images: ["/images/portfolio08.png"],
    altText: "Interface do aplicativo Purificatta Adesão exibindo opções de assinatura para purificadores de água",
    category: "mobile",
    tools: ["Ionic", "Typescript", "SASS", "Firebase"],
    description: "Aplicativo para adesão e gerenciamento de planos da Purificatta, facilitando a assinatura e suporte.",
    externalLink: "https://play.google.com/store/apps/details?id=br.com.purificatta.adesao",
    ariaLabel: "Ver detalhes do Purificatta Adesão",
    showSlide: false,
  }
];

export const participations: Project[] = [
  {
    id: "fica-na-regua",
    title: "Fica na Régua",
    images: ["/images/projects/fica-na-regua01.mp4"],
    altText: "Interface do projeto Fica na Régua mostrando um campo de busca e uma lista de barbearias mais próximas.",
    slideImage: "/images/projecs/slider-ficanaregua.png",
    category: "web",
    tools: ["React", "NextJS", "Tailwind", "Typescript"],
    description: "Sistema de busca de barbearias e agendamento de horários, desenvolvido em equipe de três pessoas. Todo o frontend foi desenvolvido por mim, utilizando React v19.0.0, NextJS v15.2.1, Tailwind v4 e Typescript. O sistema permite que o usuário busque barbearias próximas a sua localização e agende horários.",
    externalLink: "https://ficanaregua.vercel.app",
    ariaLabel: "Ver detalhes do Fica na Régua",
    showSlide: true,
  },
  {
    id: "meelnutri",
    title: "MeelNutri",
    images: ["/images/projects/meelnutri01.jpg"],
    altText: "Interface do aplicativo MeelNutri mostrando planos alimentares e acompanhamento nutricional",
    category: "mobile",
    tools: ["Ionic", "Typescript", "SASS", "Firebase"],
    description: "Aplicativo para acompanhamento nutricional, criação de planos alimentares e monitoramento de refeições.",
    externalLink: "https://play.google.com/store/apps/details?id=br.com.meelnutri",
    ariaLabel: "Ver detalhes do MeelNutri",
    showSlide: false,
  },
  {
    id: "funcorsan",
    title: "Funcorsan",
    images: ["/images/portfolio05.png"],
    altText: "Interface do aplicativo Funcorsan exibindo serviços e informações para associados",
    category: "mobile",
    tools: ["Ionic", "Angular", "Typescript", "SASS", "Firebase"],
    description: "Aplicativo para associados da Funcorsan, oferecendo acesso a serviços, documentos e informações.",
    externalLink: "https://play.google.com/store/apps/details?id=br.com.funcorsan",
    ariaLabel: "Ver detalhes do Funcorsan",
    showSlide: false,
  },
  {
    id: "laudelina2",
    title: "Laudelina",
    images: ["/images/portfolio06.png"],
    altText: "Interface do aplicativo Laudelina exibindo informações e suporte para trabalhadoras domésticas",
    category: "mobile",
    tools: ["Ionic", "Typescript", "SASS", "Firebase"],
    description: "Aplicativo voltado para trabalhadoras domésticas, oferecendo informações sobre direitos, cálculos de salários e rescisões, benefícios, pesquisa de órgãos e sindicatos da cidade e conexão com outras empregadas domésticas nas proximidades.",
    externalLink: "https://play.google.com/store/apps/details?id=br.org.laudelina",
    ariaLabel: "Ver detalhes do Laudelina",
    showSlide: false,
  }
];

export const arts: Project[] = [
  {
    id: "lands",
    title: "Tipos de Terrenos",
    images: ["/images/projects/terrenos01.png", "/images/projects/terrenos02.png", "/images/projects/terrenos03.png", "/images/projects/terrenos04.png", "/images/projects/terrenos05.png"],
    altText: "Tipos de Terrenos",
    category: "design",
    tools: ["Animate", "Photoshop"],
    description: "Estudo sobre diferentes terrenos para jogos criados no Adobe Animate e Adobe Photoshop, para o curso de Programação de Jogos Digitais.",
    externalLink: "https://www.behance.net/gallery/61701671/TerrenosLands",
    ariaLabel: "Ver detalhes",
    showSlide: false,
  },
  {
    id: "design-personagens",
    title: "Design de Personagens",
    images: ["/images/projects/personagens01.png", "/images/projects/personagens02.png", "/images/projects/personagens03.png", "/images/projects/personagens04.png", "/images/projects/personagens05.png", "/images/projects/personagens06.png", "/images/projects/personagens07.png", "/images/projects/personagens08.png"],
    altText: "Design de Personagens",
    category: "design",
    tools: ["Illustrator", "Photoshop"],
    description: "Desenhos vetorizados de monstrinhos infantis utilizados no meu trabalho de graduação do curso de Programação de Jogos Digitais.",
    externalLink: "https://www.behance.net/gallery/47743513/Design-de-Personagens",
    ariaLabel: "Ver detalhes",
    showSlide: false,
  },
  {
    id: "catalogo",
    title: "Catálogo de Animais",
    images: ["/images/projects/animais01.png", "/images/projects/animais02.png", "/images/projects/animais03.png", "/images/projects/animais04.png"],
    altText: "Artes",
    category: "design",
    tools: ["Illustrator", "Photoshop"],
    description: "Coleção de ilustrações de animais acompanhadas por lettering artístico.",
    externalLink: "https://www.behance.net/gallery/121457211/animals-catalogue",
    ariaLabel: "Ver detalhes",
    showSlide: false,
  },
  {
    id: "jogo-da-memoria",
    title: "Jogo da Memória - Frutas",
    images: ["/images/projects/jogo-memoria.png"],
    altText: "Jogo da Memória - Frutas",
    category: "design",
    tools: ["Illustrator", "Photoshop"],
    description: "Ícones de frutas criados no Photoshop e Illustrator para um jogo da memória infantil desenvolvido no curso de Programação de Jogos Digitais, em 2013.",
    externalLink: "https://www.behance.net/gallery/50276623/Jogo-da-Memoria-Frutas",
    ariaLabel: "Ver detalhes",
    showSlide: false,
  },
  {
    id: "vetorizacao",
    title: "Vetorização de Desenhos",
    images: ["/images/projects/vetorizacao01.png", "/images/projects/vetorizacao02.png", "/images/projects/vetorizacao03.png"],
    altText: "Artes",
    category: "design",
    tools: ["Illustrator", "Photoshop"],
    description: "Desenhos vetorizados de personagens feitos a partir de desenhos à mão de alguns amigos e também alguns desenhos meus.",
    externalLink: "https://www.behance.net/gallery/98439717/Vetorizacao-de-Desenhos",
    ariaLabel: "Ver detalhes",
    showSlide: false,
  },
  {
    id: "desenvolveu-tech",
    title: "Redes Sociais - desenvolveuTECH",
    images: ["/images/projects/desenvolveu01.png", "/images/projects/desenvolveu02.png", "/images/projects/desenvolveu03.png"],
    altText: "Artes",
    category: "design",
    tools: ["Illustrator", "Photoshop"],
    description: "Artes desenvolvidas para as redes sociais da empresa desenvolveuTECH.",
    externalLink: "https://www.behance.net/gallery/101824099/Artes-Redes-Sociais-desenvolveu-TECH",
    ariaLabel: "Ver detalhes",
    showSlide: false,
  },
  {
    id: "m-de-moveis",
    title: "Redes Sociais - M de Móveis",
    images: ["/images/projects/m-de-moveis01.png", "/images/projects/m-de-moveis02.png", "/images/projects/m-de-moveis03.png"],
    altText: "Artes",
    category: "design",
    tools: ["Illustrator", "Photoshop"],
    description: "Artes desenvolvidas para as redes sociais da empresa M de Móveis.",
    externalLink: "https://www.behance.net/gallery/101826925/Artes-Redes-Sociais-M-de-Moveis",
    ariaLabel: "Ver detalhes",
    showSlide: false,
  }
];  

export const featuredProjects: Project[] = [
  projects[0],
  projects[1],
  projects[2],
  participations[0],
  participations[1],
  projects[3],
];