import { Project } from "@/models/Project";

export const projects: Project[] = [
  {
    id: "dj-laud",
    title: "DJ Laud",
    images: ["/images/laud01.png"],
    altText: "Site do DJ Laud, mostrando informações sobre astreaming e eventos ao vivo",
    slideImage: "/images/slide02.png",
    category: "web",
    tools: ["Wix", "HTML", "CSS", "Javascript"],
    description: "Plataforma de streaming e eventos ao vivo, com foco em transmissões de alta qualidade e interação com o público.",
    externalLink: "https://laud.live",
    ariaLabel: "Visitar o site da Laud Live",
    featured: true,
  },
  {
    id: "terapeuta-bele",
    title: "Terapeuta Bele",
    images: ["/images/terapeuta01.png"],
    altText: "Site da Terapeuta Bele, mostrando informações sobre terapias e agendamentos",
    slideImage: "/images/slide01.png",
    category: "web",
    tools: ["Wix", "HTML", "CSS", "Javascript"],
    description: "Site profissional para a terapeuta Bele, com informações sobre serviços, blog e agendamento de consultas.",
    externalLink: "https://terapeutabele.com.br",
    ariaLabel: "Visitar o site da Terapeuta Bele",
    featured: true,
  },
  {
    id: "hostelzim",
    title: "HostelZim",
    images: ["/images/portfolio03.png"],
    altText: "Interface do sistema HostelZim mostrando uma lista de quartos e clientes",
    slideImage: "/images/slide03.png",
    category: "web",
    tools: ["React", "NextJS", "Chakra UI", "Chart.js"],
    description: "HostelZim é um sistema web desenvolvido em React para gerenciamento de um hostel. Ele permite criar, editar, excluir e listar quartos e clientes.",
    externalLink: null,
    repoLink: "https://github.com/ramou1/hostel-system",
    ariaLabel: "Ver detalhes do sistema Fatura Online",
    featured: true,
  },
  {
    id: "music-chords",
    title: "Music Chords",
    images: ["/images/portfolio04.png"],
    altText: "Interface do aplicativo Music Chords mostrando uma lista de acordes e formulário de criação de acorde",
    slideImage: "/images/slide01.png",
    category: "mobile",
    tools: ["Ionic", "Typescript"],
    description: "Aplicativo para salvar acordes de músicas.",
    externalLink: null,
    repoLink: "https://github.com/ramou1/music-chords-app",
    ariaLabel: "Ver detalhes do Music Chords",
    featured: false,
  },
  {
    id: "gimme-pizza",
    title: "Gimme Pizza",
    images: ["/images/portfolio05.png"],
    altText: "Interface do sistema de Chamados mostrando uma lista de chamados e formulário de criação de chamado",
    slideImage: "/images/slide02.png",
    category: "web",
    tools: ["Angular", "Firebase"],
    description: "Sistema para gerenciar pedidos de pizza.",
    repoLink: "https://github.com/ramou1/gimme-pizza",
    ariaLabel: "Ver detalhes do sistema",
    featured: false,
  },
  {
    id: "gestao-de-projetos",
    title: "Gestão de Projetos",
    images: ["/images/portfolio06.png"],
    altText: "Dashboard do aplicativo de Gestão de Projetos exibindo quadro Kanban com tarefas",
    slideImage: "/images/slide03.png",
    category: "design",
    tools: ["Angular", "Firebase"],
    description: "Aplicativo para gerenciar projetos e tarefas.",
    externalLink: null,
    repoLink: "https://github.com",
    ariaLabel: "Ver detalhes da Gestão de Projetos",
    featured: false,
  },
  {
    id: "sistema-de-orcamentos",
    title: "Sistema de Orçamentos",
    images: ["/images/portfolio07.png"],
    altText: "Tela do Sistema de Orçamentos mostrando um formulário de criação de orçamento e lista de orçamentos recentes",
    slideImage: "/images/slide01.png",
    category: "web",
    tools: ["Angular", "Firebase"],
    description: "Sistema para criação e envio de orçamentos.",
    externalLink: null,
    repoLink: "https://github.com",
    ariaLabel: "Ver detalhes do Sistema de Orçamentos",
    featured: false,
  },
];

export const participations: Project[] = [
  {
    id: "meelnutri2",
    title: "MeelNutri",
    images: ["/images/portfolio08.png"],
    altText: "Interface do aplicativo MeelNutri mostrando planos alimentares e acompanhamento nutricional",
    slideImage: "/images/slide01.png",
    category: "mobile",
    tools: ["Illustrator", "Photoshop"],
    description: "Aplicativo para acompanhamento nutricional, criação de planos alimentares e monitoramento de refeições.",
    externalLink: "https://play.google.com/store/apps/details?id=br.com.meelnutri",
    ariaLabel: "Ver detalhes do MeelNutri",
    featured: false,
  },
  {
    id: "funcorsan2",
    title: "Funcorsan",
    images: ["/images/portfolio09.png"],
    altText: "Interface do aplicativo Funcorsan exibindo serviços e informações para associados",
    slideImage: "/images/slide01.png",
    category: "mobile",
    tools: ["Illustrator", "Photoshop"],
    description: "Aplicativo para associados da Funcorsan, oferecendo acesso a serviços, documentos e informações.",
    externalLink: "https://play.google.com/store/apps/details?id=br.com.funcorsan",
    ariaLabel: "Ver detalhes do Funcorsan",
    featured: false,
  },
  {
    id: "laudelina2",
    title: "Laudelina",
    images: ["/images/portfolio10.png"],
    altText: "Interface do aplicativo Laudelina exibindo informações e suporte para trabalhadoras domésticas",
    slideImage: "/images/slide01.png",
    category: "mobile",
    tools: ["Illustrator", "Photoshop"],
    description: "Aplicativo voltado para trabalhadoras domésticas, oferecendo informações sobre direitos, benefícios e suporte.",
    externalLink: "https://play.google.com/store/search?q=laudelina&c=apps",
    ariaLabel: "Ver detalhes do Laudelina",
    featured: false,
  },
  {
    id: "purificatta2",
    title: "Purificatta",
    images: ["/images/portfolio03.png"],
    altText: "Interface do aplicativo Purificatta exibindo gerenciamento de assinaturas de purificadores de água",
    slideImage: "/images/slide01.png",
    category: "mobile",
    tools: ["Illustrator", "Photoshop"],
    description: "Aplicativo para clientes da Purificatta, permitindo gerenciamento de planos e acompanhamento de serviços.",
    externalLink: "https://play.google.com/store/apps/details?id=br.com.purificatta.app",
    ariaLabel: "Ver detalhes do Purificatta",
    featured: false,
  },
  {
    id: "purificatta-adesao2",
    title: "Purificatta Adesão",
    images: ["/images/portfolio04.png"],
    altText: "Interface do aplicativo Purificatta Adesão exibindo opções de assinatura para purificadores de água",
    slideImage: "/images/slide01.png",
    category: "mobile",
    tools: ["Illustrator", "Photoshop"],
    description: "Aplicativo para adesão e gerenciamento de planos da Purificatta, facilitando a assinatura e suporte.",
    externalLink: "https://play.google.com/store/apps/details?id=br.com.purificatta.adesao",
    ariaLabel: "Ver detalhes do Purificatta Adesão",
    featured: false,
  }
];

export const arts: Project[] = [
  {
    id: "lands",
    title: "Tipos de Terrenos",
    images: ["/images/portfolio05.png"],
    altText: "Tipos de Terrenos",
    slideImage: "/images/slide01.png",
    category: "design",
    tools: ["Illustrator", "Photoshop"],
    description: "Estudo sobre terrenos para o curso de Programação de Jogos Digitais.",
    externalLink: "https://www.behance.net/gallery/61701671/TerrenosLands",
    ariaLabel: "Ver detalhes",
    featured: false,
  },
  {
    id: "personagens",
    title: "Design de Personagens",
    images: ["/images/portfolio06.png"],
    altText: "Design de Personagens",
    slideImage: "/images/slide01.png",
    category: "design",
    tools: ["Illustrator", "Photoshop"],
    description: "Desenhos vetorizados de personagens utilizados no meu trabalho de graduação do curso de Programação de Jogos Digitais.",
    externalLink: "https://www.behance.net/gallery/47743513/Design-de-Personagens",
    ariaLabel: "Ver detalhes",
    featured: false,
  },
  {
    id: "jogo-da-memoria",
    title: "Jogo da Memória - Frutas",
    images: ["/images/portfolio07.png"],
    altText: "Jogo da Memória - Frutas",
    category: "design",
    tools: ["Illustrator", "Photoshop"],
    description: "Ícones de frutas para o jogo da memória desenvolvido no curso de Programação de Jogos Digitais, em 2013.",
    externalLink: "https://www.behance.net/gallery/50276623/Jogo-da-Memoria-Frutas",
    ariaLabel: "Ver detalhes",
    featured: false,
  },
  {
    id: "vetorizacao",
    title: "Vetorização de Desenhos",
    images: ["/images/portfolio08.png"],
    altText: "Artes",
    slideImage: "/images/slide01.png",
    category: "design",
    tools: ["Illustrator", "Photoshop"],
    description: "Desenhos vetorizados de personagens feitos a partir de desenhos à mão de alguns amigos e também alguns desenhos meus.",
    externalLink: "https://www.behance.net/gallery/98439717/Vetorizacao-de-Desenhos",
    ariaLabel: "Ver detalhes",
    featured: false,
  },
  {
    id: "catalogo",
    title: "Catálogo de Animais",
    images: ["/images/portfolio09.png"],
    altText: "Artes",
    slideImage: "/images/slide01.png",
    category: "design",
    tools: ["Illustrator", "Photoshop"],
    description: "Coleção de ilustrações de animais acompanhadas por lettering artístico.",
    externalLink: "https://www.behance.net/gallery/98439717/Vetorizacao-de-Desenhos",
    ariaLabel: "Ver detalhes",
    featured: false,
  },
  {
    id: "desenvolveu-tech",
    title: "Redes Sociais - desenvolveuTECH",
    images: ["/images/portfolio10.png"],
    altText: "Artes",
    slideImage: "/images/slide01.png",
    category: "design",
    tools: ["Illustrator", "Photoshop"],
    description: "Artes desenvolvidas para as redes sociais da empresa desenvolveuTECH.",
    externalLink: "https://www.behance.net/gallery/101824099/Artes-Redes-Sociais-desenvolveu-TECH",
    ariaLabel: "Ver detalhes",
    featured: false,
  },
  {
    id: "m-de-moveis",
    title: "Redes Sociais - M de Móveis",
    images: ["/images/portfolio06.png"],
    altText: "Artes",
    slideImage: "/images/slide01.png",
    category: "design",
    tools: ["Illustrator", "Photoshop"],
    description: "Artes desenvolvidas para as redes sociais da empresa M de Móveis.",
    externalLink: "https://www.behance.net/gallery/101826925/Artes-Redes-Sociais-M-de-Moveis",
    ariaLabel: "Ver detalhes",
    featured: false,
  }
];  