export const projects = [
  {
    id: "terapeuta-bele",
    title: "Terapeuta Bele",
    projectImage: "/images/portfolio01.png",
    altText: "Site da Terapeuta Bele, mostrando informações sobre terapias e agendamentos",
    slideImage: "/images/slide01.png",
    category: "Web",
    description: "Site profissional para a terapeuta Bele, com informações sobre serviços, blog e agendamento de consultas.",
    externalLink: "https://terapeutabele.com.br",
    ariaLabel: "Visitar o site da Terapeuta Bele",
    featured: true,
  },
  {
    id: "laud-live",
    title: "Laud Live",
    projectImage: "/images/portfolio02.png",
    altText: "Site da Laud Live, mostrando informações sobre astreaming e eventos ao vivo",
    slideImage: "/images/slide01.png",
    category: "Web",
    description: "Plataforma de streaming e eventos ao vivo, com foco em transmissões de alta qualidade e interação com o público.",
    externalLink: "https://laud.live",
    ariaLabel: "Visitar o site da Laud Live",
    featured: true,
  },
  {
    id: "meelnutri",
    title: "MeelNutri",
    projectImage: "/images/portfolio01.png",
    altText: "Interface do aplicativo MeelNutri mostrando planos alimentares e acompanhamento nutricional",
    slideImage: "/images/slide01.png",
    category: "Mobile",
    description: "Aplicativo para acompanhamento nutricional, criação de planos alimentares e monitoramento de refeições.",
    externalLink: "https://play.google.com/store/apps/details?id=br.com.meelnutri",
    ariaLabel: "Ver detalhes do MeelNutri",
    featured: true,
  },
  {
    id: "hostelzim",
    title: "HostelZim",
    projectImage: "/images/portfolio02.png",
    altText: "Interface do sistema HostelZim mostrando uma lista de quartos e clientes",
    slideImage: "/images/slide02.png",
    category: "Web",
    description: "HostelZim é um sistema web desenvolvido em React para gerenciamento de um hostel. Ele permite criar, editar, excluir e listar quartos e clientes.",
    externalLink: "https://github.com/ramou1/hostel-system",
    ariaLabel: "Ver detalhes do sistema Fatura Online",
    featured: false,
  },
  {
    id: "music-chords",
    title: "Music Chords",
    projectImage: "/images/portfolio03.png",
    altText: "Interface do aplicativo Music Chords mostrando uma lista de acordes e formulário de criação de acorde",
    slideImage: "/images/slide03.png",
    category: "Mobile",
    description: "Aplicativo para salvar acordes de músicas.",
    externalLink: "https://github.com/ramou1/music-chords-app",
    ariaLabel: "Ver detalhes do Music Chords",
    featured: false,
  },
  {
    id: "gimme-pizza",
    title: "Gimme Pizza",
    projectImage: "/images/portfolio04.png",
    altText: "Interface do sistema de Chamados mostrando uma lista de chamados e formulário de criação de chamado",
    slideImage: "/images/slide01.png",
    category: "Web",
    description: "Sistema para gerenciar pedidos de pizza.",
    externalLink: "https://github.com/ramou1/gimme-pizza",
    ariaLabel: "Ver detalhes do sistema",
    featured: false,
  },
  {
    id: "gestao-de-projetos",
    title: "Gestão de Projetos",
    projectImage: "/images/portfolio05.png",
    altText: "Dashboard do aplicativo de Gestão de Projetos exibindo quadro Kanban com tarefas",
    slideImage: "/images/slide01.png",
    category: "Design",
    description: "Aplicativo para gerenciar projetos e tarefas.",
    externalLink: "https://github.com",
    ariaLabel: "Ver detalhes da Gestão de Projetos",
    featured: false,
  },
  {
    id: "sistema-de-orcamentos",
    title: "Sistema de Orçamentos",
    projectImage: "/images/portfolio06.png",
    altText: "Tela do Sistema de Orçamentos mostrando um formulário de criação de orçamento e lista de orçamentos recentes",
    slideImage: "/images/slide01.png",
    category: "Web",
    description: "Sistema para criação e envio de orçamentos.",
    externalLink: "https://github.com",
    ariaLabel: "Ver detalhes do Sistema de Orçamentos",
    featured: false,
  },
];

export const participations = [
  {
    id: "meelnutri",
    title: "MeelNutri",
    projectImage: "/images/portfolio01.png",
    altText: "Interface do aplicativo MeelNutri mostrando planos alimentares e acompanhamento nutricional",
    slideImage: "/images/slide01.png",
    category: "Mobile",
    description: "Aplicativo para acompanhamento nutricional, criação de planos alimentares e monitoramento de refeições.",
    externalLink: "https://play.google.com/store/apps/details?id=br.com.meelnutri",
    ariaLabel: "Ver detalhes do MeelNutri",
    featured: false,
  },
  {
    id: "funcorsan",
    title: "Funcorsan",
    projectImage: "/images/portfolio06.png",
    altText: "Interface do aplicativo Funcorsan exibindo serviços e informações para associados",
    category: "Mobile",
    description: "Aplicativo para associados da Funcorsan, oferecendo acesso a serviços, documentos e informações.",
    externalLink: "https://play.google.com/store/apps/details?id=br.com.funcorsan",
    ariaLabel: "Ver detalhes do Funcorsan",
    featured: false,
  },
  {
    id: "laudelina",
    title: "Laudelina",
    projectImage: "/images/portfolio06.png",
    altText: "Interface do aplicativo Laudelina exibindo informações e suporte para trabalhadoras domésticas",
    category: "Mobile",
    description: "Aplicativo voltado para trabalhadoras domésticas, oferecendo informações sobre direitos, benefícios e suporte.",
    externalLink: "https://play.google.com/store/search?q=laudelina&c=apps",
    ariaLabel: "Ver detalhes do Laudelina",
    featured: false,
  },
  {
    id: "purificatta",
    title: "Purificatta",
    projectImage: "/images/portfolio06.png",
    altText: "Interface do aplicativo Purificatta exibindo gerenciamento de assinaturas de purificadores de água",
    category: "Mobile",
    description: "Aplicativo para clientes da Purificatta, permitindo gerenciamento de planos e acompanhamento de serviços.",
    externalLink: "https://play.google.com/store/apps/details?id=br.com.purificatta.app",
    ariaLabel: "Ver detalhes do Purificatta",
    featured: false,
  },
  {
    id: "purificatta-adesao",
    title: "Purificatta Adesão",
    projectImage: "/images/portfolio06.png",
    altText: "Interface do aplicativo Purificatta Adesão exibindo opções de assinatura para purificadores de água",
    category: "Mobile",
    description: "Aplicativo para adesão e gerenciamento de planos da Purificatta, facilitando a assinatura e suporte.",
    externalLink: "https://play.google.com/store/apps/details?id=br.com.purificatta.adesao",
    ariaLabel: "Ver detalhes do Purificatta Adesão",
    featured: false,
  }
];

export const arts = [
  {
    id: "meelnutri",
    title: "MeelNutri",
    projectImage: "/images/portfolio01.png",
    altText: "Interface do aplicativo MeelNutri mostrando planos alimentares e acompanhamento nutricional",
    slideImage: "/images/slide01.png",
    category: "Mobile",
    description: "Aplicativo para acompanhamento nutricional, criação de planos alimentares e monitoramento de refeições.",
    externalLink: "https://play.google.com/store/apps/details?id=br.com.meelnutri",
    ariaLabel: "Ver detalhes do MeelNutri",
    featured: false,
  },
  {
    id: "funcorsan",
    title: "Funcorsan",
    projectImage: "/images/portfolio06.png",
    altText: "Interface do aplicativo Funcorsan exibindo serviços e informações para associados",
    category: "Mobile",
    description: "Aplicativo para associados da Funcorsan, oferecendo acesso a serviços, documentos e informações.",
    externalLink: "https://play.google.com/store/apps/details?id=br.com.funcorsan",
    ariaLabel: "Ver detalhes do Funcorsan",
    featured: false,
  },
  {
    id: "laudelina",
    title: "Laudelina",
    projectImage: "/images/portfolio06.png",
    altText: "Interface do aplicativo Laudelina exibindo informações e suporte para trabalhadoras domésticas",
    category: "Mobile",
    description: "Aplicativo voltado para trabalhadoras domésticas, oferecendo informações sobre direitos, benefícios e suporte.",
    externalLink: "https://play.google.com/store/search?q=laudelina&c=apps",
    ariaLabel: "Ver detalhes do Laudelina",
    featured: false,
  },
  {
    id: "purificatta",
    title: "Purificatta",
    projectImage: "/images/portfolio06.png",
    altText: "Interface do aplicativo Purificatta exibindo gerenciamento de assinaturas de purificadores de água",
    category: "Mobile",
    description: "Aplicativo para clientes da Purificatta, permitindo gerenciamento de planos e acompanhamento de serviços.",
    externalLink: "https://play.google.com/store/apps/details?id=br.com.purificatta.app",
    ariaLabel: "Ver detalhes do Purificatta",
    featured: false,
  },
  {
    id: "purificatta-adesao",
    title: "Purificatta Adesão",
    projectImage: "/images/portfolio06.png",
    altText: "Interface do aplicativo Purificatta Adesão exibindo opções de assinatura para purificadores de água",
    category: "Mobile",
    description: "Aplicativo para adesão e gerenciamento de planos da Purificatta, facilitando a assinatura e suporte.",
    externalLink: "https://play.google.com/store/apps/details?id=br.com.purificatta.adesao",
    ariaLabel: "Ver detalhes do Purificatta Adesão",
    featured: false,
  }
];  