export const projects = [
  {
    id: 1,
    title: "Agenda de Contatos",
    image: "/images/portfolio01.png",
    category: "Mobile",
    description: "Aplicativo para salvar contatos e informações de contato.",
    externalLink: "behance.net/seu-usuario",
    link: "/projeto1",
  },
  {
    id: 2,
    title: "Fatura Online",
    image: "/images/portfolio02.png",
    category: "Web",
    description: "Sistema de gestão de faturas com assinatura digital.",
    externalLink: "https://github.com/seu-usuario/fatura-online",
    link: null,
  },
  {
    id: 3,
    title: "Registro de Vacinação",
    image: "/images/portfolio03.png",
    category: "Mobile",
    description: "Aplicativo para gerenciar certificados de vacinação.",
    externalLink: "https://github.com/seu-usuario/registro-vacinacao",
    link: "/projeto3",
  },
  {
    id: 4,
    title: "Sistema de Chamados",
    image: "/images/portfolio04.png",
    category: "Web",
    description: "Sistema para abertura e acompanhamento de chamados.",
    externalLink: "adobe.com/seu-usuario",
    link: null,
  },
  {
    id: 5,
    title: "Gestão de Projetos",
    image: "/images/portfolio05.png",
    category: "Design",
    description: "Aplicativo para gerenciar projetos e tarefas.",
    externalLink: "https://github.com",
    link: null,
  },
  {
    id: 6,
    title: "Sistema de Orçamentos",
    image: "/images/portfolio06.png",
    category: "Web",
    description: "Sistema para criação e envio de orçamentos.",
    externalLink: "https://github.com",
    link: null,
  },
];
